//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Art()
        {
            this.Auctionhistories = new HashSet<Auctionhistory>();
            this.Carts = new HashSet<Cart>();
            this.LikeLists = new HashSet<LikeList>();
            this.ReviewLists = new HashSet<ReviewList>();
            this.Transdetails = new HashSet<Transdetail>();
        }
    
        public int IDA { get; set; }
        public string NameA { get; set; }
        public int WidthA { get; set; }
        public int HeightA { get; set; }
        public int DepthA { get; set; }
        public string MaterialA { get; set; }
        public System.DateTime DaycreateA { get; set; }
        public string DescriptionA { get; set; }
        public decimal PriceA { get; set; }
        public int IDAT { get; set; }
        public int IDAS { get; set; }
        public int IDU { get; set; }
        public int IDC { get; set; }
        public int IDUC { get; set; }
        public string FilePath { get; set; }
        public int FileSize { get; set; }
        public bool StatusA { get; set; }
        public Nullable<int> LikeCount { get; set; }
    
        public virtual Artstatu Artstatu { get; set; }
        public virtual Arttype Arttype { get; set; }
        public virtual Category Category { get; set; }
        public virtual Usercategory Usercategory { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auctionhistory> Auctionhistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeList> LikeLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewList> ReviewLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transdetail> Transdetails { get; set; }
    }
}
