//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtGalleryEntities : DbContext
    {
        public ArtGalleryEntities()
            : base("name=ArtGalleryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Art> Arts { get; set; }
        public virtual DbSet<Artstatu> Artstatus { get; set; }
        public virtual DbSet<Arttype> Arttypes { get; set; }
        public virtual DbSet<Auctionhistory> Auctionhistories { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<LikeList> LikeLists { get; set; }
        public virtual DbSet<ReviewList> ReviewLists { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Transdetail> Transdetails { get; set; }
        public virtual DbSet<Transhistory> Transhistories { get; set; }
        public virtual DbSet<Transstatu> Transstatus { get; set; }
        public virtual DbSet<Usercategory> Usercategories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Usertype> Usertypes { get; set; }
        public virtual DbSet<MessageList> MessageLists { get; set; }
        public virtual DbSet<Messagetype> Messagetypes { get; set; }
    }
}
