//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageList
    {
        public int IDM { get; set; }
        public int IDUS { get; set; }
        public int IDUR { get; set; }
        public string ContentM { get; set; }
        public bool StatusM { get; set; }
        public int IDMT { get; set; }
    
        public virtual Messagetype Messagetype { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
