//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewList
    {
        public int IDR { get; set; }
        public int IDU { get; set; }
        public int IDA { get; set; }
        public string ContentR { get; set; }
    
        public virtual Art Art { get; set; }
        public virtual User User { get; set; }
    }
}
