//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transdetail
    {
        public int IDTD { get; set; }
        public int IDA { get; set; }
        public int IDTH { get; set; }
    
        public virtual Art Art { get; set; }
        public virtual Transhistory Transhistory { get; set; }
    }
}
