//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Arts = new HashSet<Art>();
            this.Auctionhistories = new HashSet<Auctionhistory>();
            this.Auctionhistories1 = new HashSet<Auctionhistory>();
            this.Carts = new HashSet<Cart>();
            this.LikeLists = new HashSet<LikeList>();
            this.ReviewLists = new HashSet<ReviewList>();
            this.Transhistories = new HashSet<Transhistory>();
            this.Usercategories = new HashSet<Usercategory>();
            this.MessageLists = new HashSet<MessageList>();
            this.MessageLists1 = new HashSet<MessageList>();
        }
    
        public int IDU { get; set; }
        public string FirstnameU { get; set; }
        public string LastnameU { get; set; }
        public string AddressU { get; set; }
        public string PhoneU { get; set; }
        public string EmailU { get; set; }
        public System.DateTime DofbU { get; set; }
        public bool SexU { get; set; }
        public string UsernameU { get; set; }
        public string PasswordU { get; set; }
        public System.DateTime DaycreateU { get; set; }
        public int IDUT { get; set; }
        public bool StatusU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Art> Arts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auctionhistory> Auctionhistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auctionhistory> Auctionhistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeList> LikeLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewList> ReviewLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transhistory> Transhistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usercategory> Usercategories { get; set; }
        public virtual Usertype Usertype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageList> MessageLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageList> MessageLists1 { get; set; }
    }
}
